version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: sol
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zoomcamp
    ports:
      - "5435:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8000:80"
